//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankh.UI.RepositoryExplorer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RepositoryStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RepositoryStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ankh.UI.RepositoryExplorer.RepositoryStrings", typeof(RepositoryStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Author.
        /// </summary>
        internal static string AuthorColumn {
            get {
                return ResourceManager.GetString("AuthorColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Directory.
        /// </summary>
        internal static string CreatingDirectory {
            get {
                return ResourceManager.GetString("CreatingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Modified.
        /// </summary>
        internal static string DateColumn {
            get {
                return ResourceManager.GetString("DateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Folder.
        /// </summary>
        internal static string ExplorerDirectoryName {
            get {
                return ResourceManager.GetString("ExplorerDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Repositories.
        /// </summary>
        internal static string LocalRepositories {
            get {
                return ResourceManager.GetString("LocalRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Lock Owner.
        /// </summary>
        internal static string LockOwnerColumn {
            get {
                return ResourceManager.GetString("LockOwnerColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Name.
        /// </summary>
        internal static string NameColumn {
            get {
                return ResourceManager.GetString("NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Revision.
        /// </summary>
        internal static string RevisionColumn {
            get {
                return ResourceManager.GetString("RevisionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subversion Repositories.
        /// </summary>
        internal static string RootName {
            get {
                return ResourceManager.GetString("RootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Size.
        /// </summary>
        internal static string SizeColumn {
            get {
                return ResourceManager.GetString("SizeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Type.
        /// </summary>
        internal static string TypeColumn {
            get {
                return ResourceManager.GetString("TypeColumn", resourceCulture);
            }
        }
    }
}
