<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>Ankh.VS.UnitTest.snk</AssemblyOriginatorKeyFile>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Stubs\**" />
    <EmbeddedResource Remove="Stubs\**" />
    <None Remove="Stubs\**" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Data" />
    <Reference Include="System.Design" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ankh.Scc\Ankh.Scc.csproj" />
    <ProjectReference Include="..\Ankh.Services\Ankh.Services.csproj" />
    <ProjectReference Include="..\Ankh.UI\Ankh.UI.csproj" />
    <ProjectReference Include="..\Ankh.Ids\Ankh.Ids.csproj" />
    <ProjectReference Include="..\Ankh.Package\Ankh.Package.csproj" />
    <ProjectReference Include="..\Ankh.VS\Ankh.VS.csproj" />
    <ProjectReference Include="..\Ankh\Ankh.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector">\n      <PrivateAssets>all</PrivateAssets>\n      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>\n    </PackageReference>\n    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.VisualStudio.SDK" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>
</Project>