<Project>
  <!-- Import the SDK Manually, to allow including the VSTools later -->
  <Import Project="$(VSToolsPath)\VSSDK\Microsoft.VsSDK.props" Condition="('$(VSToolsPath)' != '') And Exists('$(VSToolsPath)\VSSDK\Microsoft.VsSDK.props')" />
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>Ankh.Package.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <RegisterOutputPackage>true</RegisterOutputPackage>
    <RegisterWithCodebase>true</RegisterWithCodebase>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>Resources\Package.ico</ApplicationIcon>
    <GenerateVsixContainer>true</GenerateVsixContainer>
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
    <IncludeAssemblyInVSIXContainer>true</IncludeAssemblyInVSIXContainer>
    <IncludeDebugSymbolsInVSIXContainer>false</IncludeDebugSymbolsInVSIXContainer>
    <IncludeDebugSymbolsInLocalVSIXDeployment>false</IncludeDebugSymbolsInLocalVSIXDeployment>
    <CopyBuildOutputToOutputDirectory>true</CopyBuildOutputToOutputDirectory>
    <CopyOutputSymbolsToOutputDirectory>true</CopyOutputSymbolsToOutputDirectory>
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
    <UseCodebase>true</UseCodebase>
    <StartAction>Program</StartAction>
    <StartProgram Condition="'$(DevEnvDir)' != ''">$(DevEnvDir)devenv.exe</StartProgram>
    <StartArguments>/rootsuffix Exp</StartArguments>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Data" />
    <Reference Include="System.Design" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <!-- Only edit this block if you really know what you are doing; part of the command compilation -->
    <VSCTCompile Include="$(IntermediateOutputPath)..\AnkhSvn.vsct">
      <ResourceName>1000.ctmenu</ResourceName>
      <Visible>false</Visible>
    </VSCTCompile>
    <!-- The input of the ctc action is generated by a Xsl transform -->
    <!-- The result of the ctc action is automatically compiled into the following resource (MergeWithCTO) -->
    <EmbeddedResource Update="VSPackage.resx">
      <MergeWithCTO>true</MergeWithCTO>
      <SubType>Designer</SubType>
      <ManifestResourceName>VSPackage</ManifestResourceName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup Condition="'$(PlatformTarget)' != 'x86'">
    <Content Remove="x86\source.extension.VsixManifest" Condition="'$(PlatformTarget)' != 'x86'" />
  </ItemGroup>
  <ItemGroup Condition="'$(PlatformTarget)' != 'x64'">
    <Content Remove="x64\source.extension.VsixManifest" Condition="'$(PlatformTarget)' != 'x64'" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="AnkhSVN-Preview.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="LICENSE.rtf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="Package.ico">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="AnkhSvnPackage.AsyncPackage.cs" Condition="'$(UseVsSdkVersion)' &lt; '15.0'" />
    <Compile Remove="AnkhSvnPackage.LegacyPackage.cs" Condition="'$(UseVsSdkVersion)' &gt;= '15.0'" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ankh.ExtensionPoints\Ankh.ExtensionPoints.csproj" />
    <ProjectReference Include="..\Ankh.Ids\Ankh.Ids.csproj" />
    <ProjectReference Include="..\Ankh.ImageCatalog\Ankh.ImageCatalog.csproj" />
    <ProjectReference Include="..\Ankh.Scc\Ankh.Scc.csproj" />
    <ProjectReference Include="..\Ankh.Services\Ankh.Services.csproj" />
    <ProjectReference Include="..\Ankh.UI\Ankh.UI.csproj" />
    <ProjectReference Include="..\Ankh.VS.Interop\Ankh.VS.Interop.csproj" />
    <ProjectReference Include="..\Ankh.VS\Ankh.VS.csproj" />
    <ProjectReference Include="..\Ankh\Ankh.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.SDK" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" />
    <PackageReference Include="SharpSvn" GeneratePathProperty="true">
      <IncludeInVSIX>true</IncludeInVSIX>
    </PackageReference>
    <PackageReference Include="SharpSvn.UI" GeneratePathProperty="true">
      <IncludeInVSIX>true</IncludeInVSIX>
    </PackageReference>
  </ItemGroup>
  <Target Name="RemoveUnneededPlatformTargets" BeforeTargets="FindSourceVsixManifest">
    <ItemGroup>
      <None Include="x86\*.VsixManifest" Condition="'$(UseVsSdkVersion)' &lt;  '17.0'" />
      <None Include="x64\*.VsixManifest" Condition="'$(UseVsSdkVersion)' &gt;= '17.0'" />
    </ItemGroup>
  </Target>
  <Target Name="GenerateVSCT" BeforeTargets="ResolveAssemblyReferences;VSCTCompile">
    <MakeDir Directories="$(IntermediateOutputPath).." />
    <XslTransformation XmlInputPaths="$(MSBuildProjectDirectory)\Gui\AnkhSvn.xml" XslInputPath="$(MSBuildProjectDirectory)\Gui\Gui-To-Vsct.xsl" OutputPaths="$(IntermediateOutputPath)..\AnkhSvn.vsct" UseTrustedSettings="true" Parameters="&lt;Parameter Name=&quot;BitmapResId&quot; Value=&quot;Bmp_AnkhBmp&quot; /&gt;&lt;Parameter Name=&quot;Src&quot; Value=&quot;Gui\AnkhSvn.xml&quot; /&gt;&lt;Parameter Name=&quot;Configuration&quot; Value=&quot;$(Configuration)&quot; /&gt;" />
  </Target>

  <Target Name="IncludeNuGetDependenciesInVsix" BeforeTargets="FindSourceVsixManifest">
    <!-- Collect runtime dependencies from NuGet packages -->
    <ItemGroup>
      <!-- All runtime assets from NuGet packages -->
      <VSIXSourceItem Include="@(RuntimeCopyLocalItems)" Condition="'%(RuntimeCopyLocalItems.NuGetPackageId)' != '' And ! $([System.String]::Copy('%(RuntimeCopyLocalItems.NuGetPackageId)').StartsWith('Microsoft.VisualStudio.')) And ! $([System.String]::Copy('%(RuntimeCopyLocalItems.NuGetPackageId)').StartsWith('envdte')) And ! $([System.String]::Copy('%(RuntimeCopyLocalItems.NuGetPackageId)').StartsWith('VSLang'))">
        <IncludeInVSIX>true</IncludeInVSIX>
      </VSIXSourceItem>
      <VSIXSourceItem Include="@(SharpSvnExternalFiles)">
        <IncludeInVSIX>true</IncludeInVSIX>
      </VSIXSourceItem>
    </ItemGroup>
  </Target>

  <Target Name="OverrideSharpSvnWithX64" AfterTargets="IncludeNuGetDependenciesInVsix" BeforeTargets="FindSourceVsixManifest;GetVsixSourceItems" Condition="'$(UseVsSdkVersion)' &gt;= '17.0'">
    <ItemGroup>
      <VSIXSourceItem Remove="@(VSIXSourceItem)" Condition="'%(Filename)' == 'SharpSvn' Or '%(Filename)' == 'SharpSvn-DB44-20-win32' Or '%(Filename)' == 'SharpPlink-Win32'" />
      <VSIXSourceItem Include="$(PkgSharpSvn)\runtimes\win-x64\lib\net40\SharpSvn.dll">
        <IncludeInVSIX>true</IncludeInVSIX>
      </VSIXSourceItem>
      <VSIXSourceItem Include="$(PkgSharpSvn)\runtimes\win-x64\lib\netcoreapp\SharpSvn-DB44-20-x64.svnDll">
        <IncludeInVSIX>true</IncludeInVSIX>
      </VSIXSourceItem>
      <VSIXSourceItem Include="$(PkgSharpSvn)\runtimes\win-x64\lib\netcoreapp\SharpPlink-x64.svnExe">
        <IncludeInVSIX>true</IncludeInVSIX>
      </VSIXSourceItem>
    </ItemGroup>
    <Copy SourceFiles="$(PkgSharpSvn)\runtimes\win-x64\lib\net40\SharpSvn.dll" DestinationFolder="$(OutDir)" SkipUnchangedFiles="false" />
    <Copy SourceFiles="$(PkgSharpSvn)\runtimes\win-x64\lib\netcoreapp\SharpSvn-DB44-20-x64.svnDll" DestinationFolder="$(OutDir)" SkipUnchangedFiles="false" />
    <Copy SourceFiles="$(PkgSharpSvn)\runtimes\win-x64\lib\netcoreapp\SharpPlink-x64.svnExe" DestinationFolder="$(OutDir)" SkipUnchangedFiles="false" />
  </Target>

  <!-- Import SDK targetm and then the VSSDK last -->
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
  <Import Project="$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets" Condition="('$(VSToolsPath)' != '') And Exists('$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets')" />
</Project>
