//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankh.VSPackage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ankh.VSPackage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnkhSVN - Subversion Support for Visual Studio {0} 
        /// * Ankh.Package {1}
        /// * Subversion {2} via SharpSvn {3}.
        /// </summary>
        internal static string AboutDetails {
            get {
                return ResourceManager.GetString("AboutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnkhSVN is dynamically linked to: .
        /// </summary>
        internal static string AboutDynamicallyLinkedTo {
            get {
                return ResourceManager.GetString("AboutDynamicallyLinkedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnkhSVN is linked to: .
        /// </summary>
        internal static string AboutLinkedTo {
            get {
                return ResourceManager.GetString("AboutLinkedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnkhSVN is optionally linked to: .
        /// </summary>
        internal static string AboutOptionallyLinkedTo {
            get {
                return ResourceManager.GetString("AboutOptionallyLinkedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string AboutProductId {
            get {
                return ResourceManager.GetString("AboutProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnkhSVN - Subversion Support for Visual Studio.
        /// </summary>
        internal static string AboutTitleName {
            get {
                return ResourceManager.GetString("AboutTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnkhSVN - Subversion Support.
        /// </summary>
        internal static string AboutTitleNameShort {
            get {
                return ResourceManager.GetString("AboutTitleNameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Sub&amp;version.
        /// </summary>
        internal static string AddToSubversionCommandName {
            get {
                return ResourceManager.GetString("AddToSubversionCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .Net Trace handling fails. Please check your .Net machine and enterprise configuration.
        /// </summary>
        internal static string DotNetTracingFails {
            get {
                return ResourceManager.GetString("DotNetTracingFails", resourceCulture);
            }
        }
    }
}
