// This file will be processed by the MIDL tool to
// produce the type library (AnkhUserControlHost.tlb) and marshalling code.

#include "olectl.h"
import "oaidl.idl";
import "ocidl.idl";

[object, uuid(412b14b5-b2fc-463b-a97d-ee072f939a38), dual, nonextensible, helpstring("Xtreme Simplicity IAnkhUserControlHostCtlCtl Interface"), pointer_default(unique)]
interface IAnkhUserControlHostCtlCtl : IDispatch
{
	[id(1), helpstring("Host a .NET User Control within a Tool Window.")] 
	HRESULT HostUserControl(IUnknown *userControl);
};

[uuid(a346e700-ccd2-4377-a4e5-5b30275493b1), version(1.0), helpstring("Xtreme Simplicity AnkhUserControlHost 1.0 Type Library")]
library AnkhUserControlHostLib
{
	importlib("stdole2.tlb");

	[uuid(88e212e9-dba6-4ca8-a820-05a9b54a3ba5), helpstring("AnkhUserControlHostCtl Class")]
	coclass AnkhUserControlHostCtl
	{
		[default] interface IAnkhUserControlHostCtlCtl;
	};
};
