//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorReportExtractorTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorReportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorReportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErrorReportExtractorTest.ErrorReportResources", typeof(ErrorReportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EmptyReport {
            get {
                return ResourceManager.GetString("EmptyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.ArgumentException: 
        ///The path is not of a legal form.
        ///   at System.IO.Path.NormalizePathFast(String path, Boolean fullCheck)
        ///   at System.IO.Path.GetDirectoryName(String path)
        ///   at Ankh.Commands.AddItemCommand.AddFilter.Filter(SvnItem item) in N:\tmp\build\src\Ankh\Commands\AddItemCommand.cs:line 113
        ///   at Ankh.Solution.ProjectNode.GetResources(IList list, Boolean getChildItems, ResourceFilterCallback filter) in N:\tmp\build\src\Ankh\Solution\ProjectNode.cs:line 28
        ///   at Ankh.Solution.Explorer. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OldDteVersionReport {
            get {
                return ResourceManager.GetString("OldDteVersionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSvn.Core.SvnClientException: 
        ///&apos;D:\My Documents\Visual Studio 2005\Projects\isrdb&apos; is already a working copy for a different URL
        ///   at NSvn.Core.Client.Checkout(String url, String path, Revision pegRevision, Revision revision, Boolean recurse, Boolean ignoreExternals) in d:\tmp\build-57\src\nsvn.core\client.cpp:line 330
        ///   at NSvn.Core.Client.Checkout(String url, String path, Revision revision, Boolean recurse) in d:\tmp\build-57\src\nsvn.core\client.cpp:line 318
        ///   at Ankh.Commands.CheckoutRunner.Work( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Report1 {
            get {
                return ResourceManager.GetString("Report1", resourceCulture);
            }
        }
    }
}
