//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace Fines.IssueZillaLib {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class issuezilla : object, System.ComponentModel.INotifyPropertyChanged {
        
        private issue[] issueField;
        
        private string versionField;
        
        private string urlbaseField;
        
        private string maintainerField;
        
        private string exporterField;
        
        private string charsetField;
        
        private string project_domainField;
        
        private string project_nameField;
        
        private string project_idField;
        
        private string dtd_versionField;
        
        public issuezilla() {
            this.dtd_versionField = "Revision: 1.2";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("issue")]
        public issue[] issue {
            get {
                return this.issueField;
            }
            set {
                if ((this.issueField != value)) {
                    this.issueField = value;
                    this.RaisePropertyChanged("issue");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                if ((this.versionField != value)) {
                    this.versionField = value;
                    this.RaisePropertyChanged("version");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string urlbase {
            get {
                return this.urlbaseField;
            }
            set {
                if ((this.urlbaseField != value)) {
                    this.urlbaseField = value;
                    this.RaisePropertyChanged("urlbase");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maintainer {
            get {
                return this.maintainerField;
            }
            set {
                if ((this.maintainerField != value)) {
                    this.maintainerField = value;
                    this.RaisePropertyChanged("maintainer");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string exporter {
            get {
                return this.exporterField;
            }
            set {
                if ((this.exporterField != value)) {
                    this.exporterField = value;
                    this.RaisePropertyChanged("exporter");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string charset {
            get {
                return this.charsetField;
            }
            set {
                if ((this.charsetField != value)) {
                    this.charsetField = value;
                    this.RaisePropertyChanged("charset");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string project_domain {
            get {
                return this.project_domainField;
            }
            set {
                if ((this.project_domainField != value)) {
                    this.project_domainField = value;
                    this.RaisePropertyChanged("project_domain");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string project_name {
            get {
                return this.project_nameField;
            }
            set {
                if ((this.project_nameField != value)) {
                    this.project_nameField = value;
                    this.RaisePropertyChanged("project_name");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string project_id {
            get {
                return this.project_idField;
            }
            set {
                if ((this.project_idField != value)) {
                    this.project_idField = value;
                    this.RaisePropertyChanged("project_id");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dtd_version {
            get {
                return this.dtd_versionField;
            }
            set {
                if ((this.dtd_versionField != value)) {
                    this.dtd_versionField = value;
                    this.RaisePropertyChanged("dtd_version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class issue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string issue_idField;
        
        private string issue_statusField;
        
        private string priorityField;
        
        private string resolutionField;
        
        private string componentField;
        
        private string versionField;
        
        private string rep_platformField;
        
        private string assigned_toField;
        
        private string delta_tsField;
        
        private string subcomponentField;
        
        private string reporterField;
        
        private string target_milestoneField;
        
        private string issue_typeField;
        
        private string creation_tsField;
        
        private string qa_contactField;
        
        private string status_whiteboardField;
        
        private string issue_file_locField;
        
        private string votesField;
        
        private string op_sysField;
        
        private string short_descField;
        
        private string[] keywordsField;
        
        private dependson[] dependsonField;
        
        private blocks[] blocksField;
        
        private is_duplicate is_duplicateField;
        
        private has_duplicates[] has_duplicatesField;
        
        private string[] ccField;
        
        private long_desc[] long_descField;
        
        private attachment[] attachmentField;
        
        private activity[] activityField;
        
        private issueStatus_code status_codeField;
        
        private issueStatus_message status_messageField;
        
        /// <remarks/>
        public string issue_id {
            get {
                return this.issue_idField;
            }
            set {
                if ((this.issue_idField != value)) {
                    this.issue_idField = value;
                    this.RaisePropertyChanged("issue_id");
                }
            }
        }
        
        /// <remarks/>
        public string issue_status {
            get {
                return this.issue_statusField;
            }
            set {
                if ((this.issue_statusField != value)) {
                    this.issue_statusField = value;
                    this.RaisePropertyChanged("issue_status");
                }
            }
        }
        
        /// <remarks/>
        public string priority {
            get {
                return this.priorityField;
            }
            set {
                if ((this.priorityField != value)) {
                    this.priorityField = value;
                    this.RaisePropertyChanged("priority");
                }
            }
        }
        
        /// <remarks/>
        public string resolution {
            get {
                return this.resolutionField;
            }
            set {
                if ((this.resolutionField != value)) {
                    this.resolutionField = value;
                    this.RaisePropertyChanged("resolution");
                }
            }
        }
        
        /// <remarks/>
        public string component {
            get {
                return this.componentField;
            }
            set {
                if ((this.componentField != value)) {
                    this.componentField = value;
                    this.RaisePropertyChanged("component");
                }
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                if ((this.versionField != value)) {
                    this.versionField = value;
                    this.RaisePropertyChanged("version");
                }
            }
        }
        
        /// <remarks/>
        public string rep_platform {
            get {
                return this.rep_platformField;
            }
            set {
                if ((this.rep_platformField != value)) {
                    this.rep_platformField = value;
                    this.RaisePropertyChanged("rep_platform");
                }
            }
        }
        
        /// <remarks/>
        public string assigned_to {
            get {
                return this.assigned_toField;
            }
            set {
                if ((this.assigned_toField != value)) {
                    this.assigned_toField = value;
                    this.RaisePropertyChanged("assigned_to");
                }
            }
        }
        
        /// <remarks/>
        public string delta_ts {
            get {
                return this.delta_tsField;
            }
            set {
                if ((this.delta_tsField != value)) {
                    this.delta_tsField = value;
                    this.RaisePropertyChanged("delta_ts");
                }
            }
        }
        
        /// <remarks/>
        public string subcomponent {
            get {
                return this.subcomponentField;
            }
            set {
                if ((this.subcomponentField != value)) {
                    this.subcomponentField = value;
                    this.RaisePropertyChanged("subcomponent");
                }
            }
        }
        
        /// <remarks/>
        public string reporter {
            get {
                return this.reporterField;
            }
            set {
                if ((this.reporterField != value)) {
                    this.reporterField = value;
                    this.RaisePropertyChanged("reporter");
                }
            }
        }
        
        /// <remarks/>
        public string target_milestone {
            get {
                return this.target_milestoneField;
            }
            set {
                if ((this.target_milestoneField != value)) {
                    this.target_milestoneField = value;
                    this.RaisePropertyChanged("target_milestone");
                }
            }
        }
        
        /// <remarks/>
        public string issue_type {
            get {
                return this.issue_typeField;
            }
            set {
                if ((this.issue_typeField != value)) {
                    this.issue_typeField = value;
                    this.RaisePropertyChanged("issue_type");
                }
            }
        }
        
        /// <remarks/>
        public string creation_ts {
            get {
                return this.creation_tsField;
            }
            set {
                if ((this.creation_tsField != value)) {
                    this.creation_tsField = value;
                    this.RaisePropertyChanged("creation_ts");
                }
            }
        }
        
        /// <remarks/>
        public string qa_contact {
            get {
                return this.qa_contactField;
            }
            set {
                if ((this.qa_contactField != value)) {
                    this.qa_contactField = value;
                    this.RaisePropertyChanged("qa_contact");
                }
            }
        }
        
        /// <remarks/>
        public string status_whiteboard {
            get {
                return this.status_whiteboardField;
            }
            set {
                if ((this.status_whiteboardField != value)) {
                    this.status_whiteboardField = value;
                    this.RaisePropertyChanged("status_whiteboard");
                }
            }
        }
        
        /// <remarks/>
        public string issue_file_loc {
            get {
                return this.issue_file_locField;
            }
            set {
                if ((this.issue_file_locField != value)) {
                    this.issue_file_locField = value;
                    this.RaisePropertyChanged("issue_file_loc");
                }
            }
        }
        
        /// <remarks/>
        public string votes {
            get {
                return this.votesField;
            }
            set {
                if ((this.votesField != value)) {
                    this.votesField = value;
                    this.RaisePropertyChanged("votes");
                }
            }
        }
        
        /// <remarks/>
        public string op_sys {
            get {
                return this.op_sysField;
            }
            set {
                if ((this.op_sysField != value)) {
                    this.op_sysField = value;
                    this.RaisePropertyChanged("op_sys");
                }
            }
        }
        
        /// <remarks/>
        public string short_desc {
            get {
                return this.short_descField;
            }
            set {
                if ((this.short_descField != value)) {
                    this.short_descField = value;
                    this.RaisePropertyChanged("short_desc");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keywords")]
        public string[] keywords {
            get {
                return this.keywordsField;
            }
            set {
                if ((this.keywordsField != value)) {
                    this.keywordsField = value;
                    this.RaisePropertyChanged("keywords");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dependson")]
        public dependson[] dependson {
            get {
                return this.dependsonField;
            }
            set {
                if ((this.dependsonField != value)) {
                    this.dependsonField = value;
                    this.RaisePropertyChanged("dependson");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("blocks")]
        public blocks[] blocks {
            get {
                return this.blocksField;
            }
            set {
                if ((this.blocksField != value)) {
                    this.blocksField = value;
                    this.RaisePropertyChanged("blocks");
                }
            }
        }
        
        /// <remarks/>
        public is_duplicate is_duplicate {
            get {
                return this.is_duplicateField;
            }
            set {
                if ((this.is_duplicateField != value)) {
                    this.is_duplicateField = value;
                    this.RaisePropertyChanged("is_duplicate");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("has_duplicates")]
        public has_duplicates[] has_duplicates {
            get {
                return this.has_duplicatesField;
            }
            set {
                if ((this.has_duplicatesField != value)) {
                    this.has_duplicatesField = value;
                    this.RaisePropertyChanged("has_duplicates");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cc")]
        public string[] cc {
            get {
                return this.ccField;
            }
            set {
                if ((this.ccField != value)) {
                    this.ccField = value;
                    this.RaisePropertyChanged("cc");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("long_desc")]
        public long_desc[] long_desc {
            get {
                return this.long_descField;
            }
            set {
                if ((this.long_descField != value)) {
                    this.long_descField = value;
                    this.RaisePropertyChanged("long_desc");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attachment")]
        public attachment[] attachment {
            get {
                return this.attachmentField;
            }
            set {
                if ((this.attachmentField != value)) {
                    this.attachmentField = value;
                    this.RaisePropertyChanged("attachment");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("activity")]
        public activity[] activity {
            get {
                return this.activityField;
            }
            set {
                if ((this.activityField != value)) {
                    this.activityField = value;
                    this.RaisePropertyChanged("activity");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public issueStatus_code status_code {
            get {
                return this.status_codeField;
            }
            set {
                if ((this.status_codeField != value)) {
                    this.status_codeField = value;
                    this.RaisePropertyChanged("status_code");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public issueStatus_message status_message {
            get {
                return this.status_messageField;
            }
            set {
                if ((this.status_messageField != value)) {
                    this.status_messageField = value;
                    this.RaisePropertyChanged("status_message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum issueStatus_code {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("200")]
        Item200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("401")]
        Item401,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("404")]
        Item404,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum issueStatus_message {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Unauthorized,
        
        /// <remarks/>
        NotFound,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class long_desc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string whoField;
        
        private string issue_whenField;
        
        private string thetextField;
        
        /// <remarks/>
        public string who {
            get {
                return this.whoField;
            }
            set {
                if ((this.whoField != value)) {
                    this.whoField = value;
                    this.RaisePropertyChanged("who");
                }
            }
        }
        
        /// <remarks/>
        public string issue_when {
            get {
                return this.issue_whenField;
            }
            set {
                if ((this.issue_whenField != value)) {
                    this.issue_whenField = value;
                    this.RaisePropertyChanged("issue_when");
                }
            }
        }
        
        /// <remarks/>
        public string thetext {
            get {
                return this.thetextField;
            }
            set {
                if ((this.thetextField != value)) {
                    this.thetextField = value;
                    this.RaisePropertyChanged("thetext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class dependson : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string issue_idField;
        
        private string whoField;
        
        private string whenField;
        
        /// <remarks/>
        public string issue_id {
            get {
                return this.issue_idField;
            }
            set {
                if ((this.issue_idField != value)) {
                    this.issue_idField = value;
                    this.RaisePropertyChanged("issue_id");
                }
            }
        }
        
        /// <remarks/>
        public string who {
            get {
                return this.whoField;
            }
            set {
                if ((this.whoField != value)) {
                    this.whoField = value;
                    this.RaisePropertyChanged("who");
                }
            }
        }
        
        /// <remarks/>
        public string when {
            get {
                return this.whenField;
            }
            set {
                if ((this.whenField != value)) {
                    this.whenField = value;
                    this.RaisePropertyChanged("when");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class blocks : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string issue_idField;
        
        private string whoField;
        
        private string whenField;
        
        /// <remarks/>
        public string issue_id {
            get {
                return this.issue_idField;
            }
            set {
                if ((this.issue_idField != value)) {
                    this.issue_idField = value;
                    this.RaisePropertyChanged("issue_id");
                }
            }
        }
        
        /// <remarks/>
        public string who {
            get {
                return this.whoField;
            }
            set {
                if ((this.whoField != value)) {
                    this.whoField = value;
                    this.RaisePropertyChanged("who");
                }
            }
        }
        
        /// <remarks/>
        public string when {
            get {
                return this.whenField;
            }
            set {
                if ((this.whenField != value)) {
                    this.whenField = value;
                    this.RaisePropertyChanged("when");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class is_duplicate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string issue_idField;
        
        private string whoField;
        
        private string whenField;
        
        /// <remarks/>
        public string issue_id {
            get {
                return this.issue_idField;
            }
            set {
                if ((this.issue_idField != value)) {
                    this.issue_idField = value;
                    this.RaisePropertyChanged("issue_id");
                }
            }
        }
        
        /// <remarks/>
        public string who {
            get {
                return this.whoField;
            }
            set {
                if ((this.whoField != value)) {
                    this.whoField = value;
                    this.RaisePropertyChanged("who");
                }
            }
        }
        
        /// <remarks/>
        public string when {
            get {
                return this.whenField;
            }
            set {
                if ((this.whenField != value)) {
                    this.whenField = value;
                    this.RaisePropertyChanged("when");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class has_duplicates : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string issue_idField;
        
        private string whoField;
        
        private string whenField;
        
        /// <remarks/>
        public string issue_id {
            get {
                return this.issue_idField;
            }
            set {
                if ((this.issue_idField != value)) {
                    this.issue_idField = value;
                    this.RaisePropertyChanged("issue_id");
                }
            }
        }
        
        /// <remarks/>
        public string who {
            get {
                return this.whoField;
            }
            set {
                if ((this.whoField != value)) {
                    this.whoField = value;
                    this.RaisePropertyChanged("who");
                }
            }
        }
        
        /// <remarks/>
        public string when {
            get {
                return this.whenField;
            }
            set {
                if ((this.whenField != value)) {
                    this.whenField = value;
                    this.RaisePropertyChanged("when");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class attachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mimetypeField;
        
        private string attachidField;
        
        private string dateField;
        
        private string descField;
        
        private string[] ispatchField;
        
        private string filenameField;
        
        private string submitter_idField;
        
        private string submitting_usernameField;
        
        private string dataField;
        
        private string attachment_iz_urlField;
        
        private string encodingField;
        
        public attachment() {
            this.encodingField = "Base64";
        }
        
        /// <remarks/>
        public string mimetype {
            get {
                return this.mimetypeField;
            }
            set {
                if ((this.mimetypeField != value)) {
                    this.mimetypeField = value;
                    this.RaisePropertyChanged("mimetype");
                }
            }
        }
        
        /// <remarks/>
        public string attachid {
            get {
                return this.attachidField;
            }
            set {
                if ((this.attachidField != value)) {
                    this.attachidField = value;
                    this.RaisePropertyChanged("attachid");
                }
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField != value)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        /// <remarks/>
        public string desc {
            get {
                return this.descField;
            }
            set {
                if ((this.descField != value)) {
                    this.descField = value;
                    this.RaisePropertyChanged("desc");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ispatch")]
        public string[] ispatch {
            get {
                return this.ispatchField;
            }
            set {
                if ((this.ispatchField != value)) {
                    this.ispatchField = value;
                    this.RaisePropertyChanged("ispatch");
                }
            }
        }
        
        /// <remarks/>
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                if ((this.filenameField != value)) {
                    this.filenameField = value;
                    this.RaisePropertyChanged("filename");
                }
            }
        }
        
        /// <remarks/>
        public string submitter_id {
            get {
                return this.submitter_idField;
            }
            set {
                if ((this.submitter_idField != value)) {
                    this.submitter_idField = value;
                    this.RaisePropertyChanged("submitter_id");
                }
            }
        }
        
        /// <remarks/>
        public string submitting_username {
            get {
                return this.submitting_usernameField;
            }
            set {
                if ((this.submitting_usernameField != value)) {
                    this.submitting_usernameField = value;
                    this.RaisePropertyChanged("submitting_username");
                }
            }
        }
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                if ((this.dataField != value)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        /// <remarks/>
        public string attachment_iz_url {
            get {
                return this.attachment_iz_urlField;
            }
            set {
                if ((this.attachment_iz_urlField != value)) {
                    this.attachment_iz_urlField = value;
                    this.RaisePropertyChanged("attachment_iz_url");
                }
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string encoding {
            get {
                return this.encodingField;
            }
            set {
                if ((this.encodingField != value)) {
                    this.encodingField = value;
                    this.RaisePropertyChanged("encoding");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class activity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userField;
        
        private string whenField;
        
        private string field_nameField;
        
        private string field_descField;
        
        private string oldvalueField;
        
        private string newvalueField;
        
        /// <remarks/>
        public string user {
            get {
                return this.userField;
            }
            set {
                if ((this.userField != value)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        /// <remarks/>
        public string when {
            get {
                return this.whenField;
            }
            set {
                if ((this.whenField != value)) {
                    this.whenField = value;
                    this.RaisePropertyChanged("when");
                }
            }
        }
        
        /// <remarks/>
        public string field_name {
            get {
                return this.field_nameField;
            }
            set {
                if ((this.field_nameField != value)) {
                    this.field_nameField = value;
                    this.RaisePropertyChanged("field_name");
                }
            }
        }
        
        /// <remarks/>
        public string field_desc {
            get {
                return this.field_descField;
            }
            set {
                if ((this.field_descField != value)) {
                    this.field_descField = value;
                    this.RaisePropertyChanged("field_desc");
                }
            }
        }
        
        /// <remarks/>
        public string oldvalue {
            get {
                return this.oldvalueField;
            }
            set {
                if ((this.oldvalueField != value)) {
                    this.oldvalueField = value;
                    this.RaisePropertyChanged("oldvalue");
                }
            }
        }
        
        /// <remarks/>
        public string newvalue {
            get {
                return this.newvalueField;
            }
            set {
                if ((this.newvalueField != value)) {
                    this.newvalueField = value;
                    this.RaisePropertyChanged("newvalue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
