#!/bin/sh

grep "http://www.apache.org/licenses/LICENSE-2.0" "$1" > /dev/null && exit 0
grep "<auto-generated>" "$1" > /dev/null && exit 0
echo "Processing $1"
YEAR=`svn log -r 0:HEAD "$1" --limit 1 | egrep "^r[0-9]" | sed -E -e 's/.*([0-9]{4})-[0-9]+-[0-9]+.*/\1/'`
NOWYEAR=`date +%Y`

svn ps svn:eol-style "native" "$1"
svn ps svn:keywords "Id" "$1"
mv "$1" "$1.tmp"
cat header.txt | \
   sed -e "s/YYYY/$YEAR/" | \
   sed -e "s/ZZZZ/$NOWYEAR/" | \
   sed -e "s/$YEAR-$YEAR/$YEAR/" > "$1.hdr"
utf-combine "$1" "$1.hdr" "$1.tmp" || cat "$1.hdr" "$1.tmp" > "$1"
rm "$1.tmp" "$1.hdr"
