//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankh.UI.SvnLog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ankh.UI.SvnLog.LogStrings", typeof(LogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        internal static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Compare revision {0} to {1}.
        /// </summary>
        internal static string CompareRevisionXToY {
            get {
                return ResourceManager.GetString("CompareRevisionXToY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create &amp;branch/tag from revision {0}.
        /// </summary>
        internal static string CreateBranchTagFromRevisionX {
            get {
                return ResourceManager.GetString("CreateBranchTagFromRevisionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: {0}.
        /// </summary>
        internal static string LogAuthor {
            get {
                return ResourceManager.GetString("LogAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0:F}.
        /// </summary>
        internal static string LogDate {
            get {
                return ResourceManager.GetString("LogDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        internal static string LogMessagePrefix {
            get {
                return ResourceManager.GetString("LogMessagePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ---- .
        /// </summary>
        internal static string LogMessageSuffix {
            get {
                return ResourceManager.GetString("LogMessageSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision: {0}.
        /// </summary>
        internal static string LogRevision {
            get {
                return ResourceManager.GetString("LogRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        internal static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Changed.
        /// </summary>
        internal static string ModifiedTextOnly {
            get {
                return ResourceManager.GetString("ModifiedTextOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plus {
            get {
                object obj = ResourceManager.GetObject("Plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties Changed.
        /// </summary>
        internal static string PropertiesModified {
            get {
                return ResourceManager.GetString("PropertiesModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced.
        /// </summary>
        internal static string Replaced {
            get {
                return ResourceManager.GetString("Replaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Revision Properties.
        /// </summary>
        internal static string RetrievingRevisionProperties {
            get {
                return ResourceManager.GetString("RetrievingRevisionProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Revert changes from revision {0}.
        /// </summary>
        internal static string RevertChangesFromRevisionX {
            get {
                return ResourceManager.GetString("RevertChangesFromRevisionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Revert changes from revision {0} to {1}.
        /// </summary>
        internal static string RevertChangesFromRevisionXToY {
            get {
                return ResourceManager.GetString("RevertChangesFromRevisionXToY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverting.
        /// </summary>
        internal static string Reverting {
            get {
                return ResourceManager.GetString("Reverting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Switch to revision {0}.
        /// </summary>
        internal static string SwitchToRevisionX {
            get {
                return ResourceManager.GetString("SwitchToRevisionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Revision Properties.
        /// </summary>
        internal static string UpdatingRevisionProperties {
            get {
                return ResourceManager.GetString("UpdatingRevisionProperties", resourceCulture);
            }
        }
    }
}
