<Project>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
    <SatelliteResourceLanguages>en;en-US</SatelliteResourceLanguages>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateResourceUsePreserializedResources>false</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <PropertyGroup>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">17.0</VisualStudioVersion>
    <UseVsSdkVersion Condition="'$(UseVsSdkVersion)' == ''">$(VisualStudioVersion)</UseVsSdkVersion>
    <PlatformTarget Condition="'$(UseVsSdkVersion)' >= '17.0'">AnyCPU</PlatformTarget>
    <SharpSvnPlatform Condition="'$(UseVsSdkVersion)' >= '17.0'">x64</SharpSvnPlatform>
  </PropertyGroup>
</Project>
