<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">17.0</VisualStudioVersion>
  </PropertyGroup>  
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageVersion Include="Microsoft.VisualStudio.SDK" Version="17.5.33428.388" />
    <PackageVersion Include="Microsoft.VSSDK.BuildTools" Version="17.5.4072" />
    <PackageVersion Include="Moq" Version="4.20.69" />
    <PackageVersion Include="NUnit" Version="3.13.3" />
    <PackageVersion Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageVersion Include="RhinoMocks" Version="3.6.1" />
    <PackageVersion Include="SharpSvn" Version="1.14003.272" />
    <PackageVersion Include="SharpSvn.UI" Version="1.14003.272" />
    <PackageVersion Include="System.Resources.Extensions" Version="9.0.0" />
    <PackageVersion Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" />
  </ItemGroup>
</Project>
